project:
  type: website

website:
  title: "BUS220"
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - href: about.qmd
        text: CheatSheet 

sidebar:
  pinned: true
  align: center
  
format:
  html:
    page-layout: full
    theme: 
      light: cosmo
      dark: slate
    css: styles.css
    code-overflow: wrap
    toc: true
    
    

editor: visual

